### ISSUE TITLE
consensus policy is unclear and it's not trustless

### ISSUE THREAD

**Issue by 0x13a** [zerocracy/zold#1]
> The list of friends is hard-coded in the software. It includes only the nodes that are trusted by the creators of this software.

This is not a trustless consensus strategy. The all point of cryptocurrency is have no trust whether here is clear that this is not the case. What happens if those _trusted_ nodes get hacked? Why should I use Zerocracy crypto-currency instead of VISA at this point?

> The list may be extended in runtime, using the statistics of the most actively contributing nodes

_most actively contributing_ based on what? The ones processing more transactions? Can this lead to a 51% attack since the network is going to be really small? 

I like the idea, but I think there is a huge underestimation of the challenges in the problem space

**Comment by 0crat** [comment]
@0x13a[/z](https://www.0crat.com/u/0x13a) I'm not managing this repo, remove the [webhook](https://github.com/zerocracy/zold/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0x13a you are right, that's the key concern we are having now. Let us work/think about it a bit more and update the draft.

**Comment by yegor256** [comment]
@0x13a I completely rewrote the description, please check again.

**Comment by 0crat** [comment]
Job `gh:zerocracy/zold#1` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#1](https://github.com/zerocracy/zold/issues/1) was not in scope
