### ISSUE TITLE
plain text instead of XML

### ISSUE THREAD

**Issue by yegor256** [zerocracy/zold#16]
Let's use plain text, it's shorter

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.8`

**Comment by 0crat** [comment]
Job `gh:zerocracy/zold#16` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#16](https://github.com/zerocracy/zold/issues/16) was not in scope
