### ISSUE TITLE
cannot start node - undefined method `find' for nil:NilClass

### ISSUE THREAD

**Issue by yv9sjrfadz** [zerocracy/zold#63]
zold node --invoice=132d71bf1f7d1d97 --trace

```
> ERROR: undefined method `find' for nil:NilClass (NoMethodError)
/var/lib/gems/2.5.0/gems/zold-0.9/lib/zold/commands/invoice.rb:51:in `run'
/var/lib/gems/2.5.0/gems/zold-0.9/lib/zold/commands/node.rb:100:in `run'
/var/lib/gems/2.5.0/gems/zold-0.9/bin/zold:127:in `<top (required)>'
/usr/local/bin/zold:23:in `load'
/usr/local/bin/zold:23:in `<main>'
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yv9sjrfadz[/z](https://www.0crat.com/u/yv9sjrfadz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@yv9sjrfadz[/z](https://www.0crat.com/u/yv9sjrfadz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.6`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-335-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 2 existing ones (Close job;{job=gh:zerocracy/zold#63, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#63, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471621195">
   <created>2018-05-27T16:13:27.955Z</created>
   <type>Close job</type>
   <token>github;zerocracy/zold;63</token>
   <author>yegor256</author>
   <params>
      <param name="job">gh:zerocracy/zold#63</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-05-27T16:28:27.956Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#63, Action: `closed`

**Comment by yegor256** [comment]
@yv9sjrfadz should be fixed

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: AsyncFlush-1
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zerocracy/zold#63] declared for identity constraint of element "blanks".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: [1471621195](https://www.0crat.com/C91QJT4CF/1471621195), Type: "Close job", Author: "yegor256"
