### ISSUE TITLE
comparison of NilClass with 0 failed

### ISSUE THREAD

**Issue by yegor256** [zerocracy/zold#66]
```
comparison of NilClass with 0 failed
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/commands/merge.rb:64:in `sort_by'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/commands/merge.rb:64:in `merge'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/commands/merge.rb:54:in `block in run'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/commands/merge.rb:52:in `each'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/commands/merge.rb:52:in `run'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/node/entrance.rb:79:in `push_unsafe'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/node/entrance.rb:52:in `block in push'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/node/entrance.rb:51:in `synchronize'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/node/entrance.rb:51:in `push'
	/var/lib/gems/2.3.0/gems/zold-0.9.2/lib/zold/node/front.rb:116:in `block in <class:Front>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.3`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-40-thread-1
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#66, Action: `assigned`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-41-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 2 existing ones (Request order start;{login=yegor256, job=gh:zerocracy/zold#66, reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)},Request order start;{login=yegor256, job=gh:zerocracy/zold#66, reason=GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471151340">
   <created>2018-05-27T11:51:28.094Z</created>
   <type>Request order start</type>
   <token>github;zerocracy/zold;66</token>
   <author>yegor256</author>
   <params>
      <param name="login">yegor256</param>
      <param name="job">gh:zerocracy/zold#66</param>
      <param name="reason">GitHub issue was assigned by @yegor256[/z](https://www.0crat.com/u/yegor256)</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#66, Action: `assigned`

**Comment by 0crat** [comment]
The job [#66](https://github.com/zerocracy/zold/issues/66) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C91QJT4CF/1471151343); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@393ec7f9

**Comment by 0crat** [comment]
Job `gh:zerocracy/zold#66` already assigned to @yegor256, can't assign to @yegor256

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-94-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 2 existing ones (Close job;{job=gh:zerocracy/zold#66, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#66, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471242048">
   <created>2018-05-27T12:40:07.432Z</created>
   <type>Close job</type>
   <token>github;zerocracy/zold;66</token>
   <author>yegor256</author>
   <params>
      <param name="job">gh:zerocracy/zold#66</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-05-27T12:55:07.433Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#66, Action: `closed`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#66](https://github.com/zerocracy/zold/issues/66) is now out of scope
