### ISSUE TITLE
Node refuses to run

### ISSUE THREAD

**Issue by biboran** [zerocracy/zold#70]
`zold node --invoice 45fc3916b5274ed1` always returns with an error: `ERROR: Wallet doesn't exist, do 'fetch' first (RuntimeError)`

I created the address (`45fc3916b5274ed1`) as specified in the documentation. I did `zold push` with and `zold fetch 45fc3916b5274ed1` with successful returns.

Am I missing something or is it a bug?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@biboran[/z](https://www.0crat.com/u/biboran) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C91QJT4CF) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@biboran please, post your full stacktrace

**Comment by biboran** [comment]
@yegor256 I am using a CLI and that's all I'm getting, no stacktrace.

**Comment by 0pdd** [comment]
@biboran the puzzle [#72](https://github.com/zerocracy/zold/issues/72) is still not solved.

**Comment by yegor256** [comment]
@biboran use `--trace` option. But I think it's fixed now: b68f9de

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.7`

**Comment by yegor256** [comment]
@biboran check version 0.9.7, should work

**Comment by biboran** [comment]
@yegor256 that seems to fix it.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: pool-639-thread-1
com.zerocracy.pm.Claims[113] java.lang.IllegalStateException: Duplicate claims are not allowed in [C91QJT4CF](https://www.0crat.com/p/C91QJT4CF), can't add this XML to 2 existing ones (Close job;{job=gh:zerocracy/zold#70, reason=GitHub issue was closed},Close job;{job=gh:zerocracy/zold#70, reason=GitHub issue was closed}):
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1471927700">
   <created>2018-05-27T19:14:58.352Z</created>
   <type>Close job</type>
   <token>github;zerocracy/zold;70</token>
   <author>biboran</author>
   <params>
      <param name="job">gh:zerocracy/zold#70</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-05-27T19:29:58.353Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: zerocracy/zold#70, Action: `closed`

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@6a151509-d0d4-40fa-a569-53d8cdf9ca67, thread: AsyncFlush-5
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:zerocracy/zold#70] declared for identity constraint of element "blanks".
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: [1471927700](https://www.0crat.com/C91QJT4CF/1471927700), Type: "Close job", Author: "biboran"

**Comment by 0pdd** [comment]
@biboran the puzzle [#78](https://github.com/yegor256/zold/issues/78) is still not solved.

**Comment by 0pdd** [comment]
@biboran the puzzle [#124](https://github.com/zold-io/zold/issues/124) is still not solved.
