### ISSUE TITLE
validate

### ISSUE THREAD

**Issue by yegor256** [zerocracy/zold#9]
Let's add a command to validate a wallet.

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.5`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.5`

**Comment by 0crat** [comment]
Job `gh:zerocracy/zold#9` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#9](https://github.com/zerocracy/zold/issues/9) was not in scope
